[package]
name = "tungsten_score"
version = "0.5.1"
edition = "2024"

description = "Windows Security Assessment Tool"
license = "MIT"
repository = "https://github.com/dw1210/TungstenScore"
homepage = "https://dw1210.github.io/TungstenScore-website/"

authors = ["dw1210 <mail@triplecolons.dev>"]

rust-version = "1.88"

[dependencies]
winreg = "0.52"
windows_firewall = "0.7"
wmi = "0.13"
serde = { version = "1.0", features = ["derive"] }
windows = "0.62"
is_elevated = "0.1"